language: python
python:
  - "2.7"
  - "3.6.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - pytest --cov=app
  - coveralls
after-success:
  - coveralls 